spring:
    profiles:
      active: local
      group:
        local:
          - common
        dev:
          - common
---
spring:
    config:
      activate:
        on-profile: common

#  jwt:
#    secret-key: 2023-wanted-internship-siren-order-project.secret_key
#    access-token.expire-time-ms: 43200000 #12시간
#    refresh-token.expired-time-ms: 604800000 #7일

jwt:
  header: Authorization
  secret: c3ByaW5nLXNlY3VyaXR5LXlvb25qdWhvLXN0dWR5LXNwcmluZy1mcmFtZXdvcmstaW4tdW5pdmVyc2l0eS1hYmNkZWZnaGlqa2xtbm9wcXJzdHV2d3h5ei1sb3ZlbWUtaS1oYXRlLXlvdQ==
  token-validity-in-seconds: 86400


---

spring:
    config:
      activate:
        on-profile: local
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ${DATASOURCE_URL_LOCAL}
      username: ${DATASOURCE_USERNAME}
      password: ${DATASOURCE_PASSWORD}
    jpa:
      hibernate:
        ddl-auto: update #create update none
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate:
          format_sql: true
          show_sql: true
      database-platform: org.hibernate.dialect.MySQL8Dialect

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
